### ISSUE TITLE
RTX 5090显卡下按照markdown里的环境部署vllm版，报错问题

### ISSUE THREAD

**Issue by jhckevin** [deepseek-ai/DeepSeek-OCR#53]
(deepseek-ocr) root@DESKTOP-P5779U6:~/projects/deepseek-ocr/DeepSeek-OCR/DeepSeek-OCR-master/DeepSeek-OCR-vllm# python run_dpsk_ocr_image.py
INFO 10-22 01:53:29 [__init__.py:239] Automatically detected platform cuda.
config.json: 2.67kB [00:00, 14.8MB/s]
INFO 10-22 01:53:35 [config.py:456] Overriding HF config with {'architectures': ['DeepseekOCRForCausalLM']}
INFO 10-22 01:53:35 [config.py:717] This model supports multiple tasks: {'reward', 'classify', 'generate', 'embed', 'score'}. Defaulting to 'generate'.
INFO 10-22 01:53:35 [llm_engine.py:240] Initializing a V0 LLM engine (v0.8.5) with config: model='deepseek-ai/DeepSeek-OCR', speculative_config=None, tokenizer='deepseek-ai/DeepSeek-OCR', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=deepseek-ai/DeepSeek-OCR, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False,
WARNING 10-22 01:53:38 [interface.py:314] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
INFO 10-22 01:53:38 [cuda.py:292] Using Flash Attention backend.
/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/torch/cuda/__init__.py:235: UserWarning:
NVIDIA GeForce RTX 5090 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_37 sm_90.
If you want to use the NVIDIA GeForce RTX 5090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
[W1022 01:53:48.759155379 socket.cpp:204] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W1022 01:53:58.769698013 socket.cpp:204] [c10d] The hostname of the client socket cannot be retrieved. err=-3
INFO 10-22 01:53:58 [parallel_state.py:1004] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 10-22 01:53:58 [model_runner.py:1108] Starting to load model deepseek-ai/DeepSeek-OCR...
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/projects/deepseek-ocr/DeepSeek-OCR/DeepSeek-OCR-master/DeepSeek-OCR-vllm/run_dpsk_ocr_image.py", line 220, in <module>
[rank0]:     result_out = asyncio.run(stream_generate(image_features, prompt))
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/asyncio/runners.py", line 195, in run
[rank0]:     return runner.run(main)
[rank0]:            ^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/asyncio/runners.py", line 118, in run
[rank0]:     return self._loop.run_until_complete(task)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
[rank0]:     return future.result()
[rank0]:            ^^^^^^^^^^^^^^^
[rank0]:   File "/root/projects/deepseek-ocr/DeepSeek-OCR/DeepSeek-OCR-master/DeepSeek-OCR-vllm/run_dpsk_ocr_image.py", line 160, in stream_generate
[rank0]:     engine = AsyncLLMEngine.from_engine_args(engine_args)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/engine/async_llm_engine.py", line 684, in from_engine_args
[rank0]:     return async_engine_cls.from_vllm_config(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/engine/async_llm_engine.py", line 657, in from_vllm_config
[rank0]:     return cls(
[rank0]:            ^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/engine/async_llm_engine.py", line 612, in __init__
[rank0]:     self.engine = self._engine_class(*args, **kwargs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/engine/async_llm_engine.py", line 267, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 275, in __init__
[rank0]:     self.model_executor = executor_class(vllm_config=vllm_config)
[rank0]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 52, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
[rank0]:     self.collective_rpc("load_model")
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
[rank0]:     answer = run_method(self.driver_worker, method, args, kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/utils.py", line 2456, in run_method
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/worker/worker.py", line 203, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1111, in load_model
[rank0]:     self.model = get_model(vllm_config=self.vllm_config)
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/model_executor/model_loader/__init__.py", line 14, in get_model
[rank0]:     return loader.load_model(vllm_config=vllm_config)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 452, in load_model
[rank0]:     model = _initialize_model(vllm_config=vllm_config)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 133, in _initialize_model
[rank0]:     return model_class(vllm_config=vllm_config, prefix=prefix)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/projects/deepseek-ocr/DeepSeek-OCR/DeepSeek-OCR-master/DeepSeek-OCR-vllm/deepseek_ocr.py", line 288, in __init__
[rank0]:     self.sam_model = build_sam_vit_b()
[rank0]:                      ^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/projects/deepseek-ocr/DeepSeek-OCR/DeepSeek-OCR-master/DeepSeek-OCR-vllm/deepencoder/sam_vary_sdpa.py", line 482, in build_sam_vit_b
[rank0]:     return _build_sam(
[rank0]:            ^^^^^^^^^^^
[rank0]:   File "/root/projects/deepseek-ocr/DeepSeek-OCR/DeepSeek-OCR-master/DeepSeek-OCR-vllm/deepencoder/sam_vary_sdpa.py", line 502, in _build_sam
[rank0]:     image_encoder=ImageEncoderViT(
[rank0]:                   ^^^^^^^^^^^^^^^^
[rank0]:   File "/root/projects/deepseek-ocr/DeepSeek-OCR/DeepSeek-OCR-master/DeepSeek-OCR-vllm/deepencoder/sam_vary_sdpa.py", line 118, in __init__
[rank0]:     self.patch_embed = PatchEmbed(
[rank0]:                        ^^^^^^^^^^^
[rank0]:   File "/root/projects/deepseek-ocr/DeepSeek-OCR/DeepSeek-OCR-master/DeepSeek-OCR-vllm/deepencoder/sam_vary_sdpa.py", line 470, in __init__
[rank0]:     self.proj = nn.Conv2d(
[rank0]:                 ^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 521, in __init__
[rank0]:     super().__init__(
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 176, in __init__
[rank0]:     self.reset_parameters()
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 182, in reset_parameters
[rank0]:     init.kaiming_uniform_(self.weight, a=math.sqrt(5))
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/torch/nn/init.py", line 500, in kaiming_uniform_
[rank0]:     return torch.overrides.handle_torch_function(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/torch/overrides.py", line 1720, in handle_torch_function
[rank0]:     result = mode.__torch_function__(public_api, types, args, kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/torch/utils/_device.py", line 104, in __torch_function__
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/anaconda3/envs/deepseek-ocr/lib/python3.12/site-packages/torch/nn/init.py", line 518, in kaiming_uniform_
[rank0]:     return tensor.uniform_(-bound, bound, generator=generator)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: no kernel image is available for execution on the device
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

很不幸，按照官方标准的环境配置，会在50系显卡上报错：RuntimeError: CUDA error: no kernel image is available for execution on the device

我应该将环境提升到cuda13+pytorch2.10夜版还是 应该 卸载掉flash attention并改用transformer呢？或者用其他方案呢？

**Comment by jhckevin** [comment]
哦，对了，使用的是WSL2和cuda 13.0

**Comment by newlxj** [comment]
vllm是报错一直没成功,你用这个吧 #46

**Comment by guesswhoam** [comment]
老哥 解决了吗？ 我用5060ti 运行之后和你这个一样的报错

**Comment by MelaHu763176** [comment]
> 老哥 解决了吗？ 我用5060ti 运行之后和你这个一样的报错

5060 ti 16G和你一样，解决了劳烦通知下

**Comment by guesswhoam** [comment]
你好，那个问题解决了。时间有点久了，问ai解决的，我只能记得一个大概，主要就是那几个库的版本问题，
Python: 3.12.12
Torch: 2.8.0+cu128 (CUDA 12.8, Available=True)
Wed Nov 12 17:21:23 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.64.01 Driver Version: 576.88 CUDA Version: 12.9 |
Version: 0.8.5+cu128；这是我安装成功的版本，供你参考。



在 2025-11-11 21:49:08，"melahoo" ***@***.***> 写道：

MelaHu763176 left a comment (deepseek-ai/DeepSeek-OCR#53)

老哥 解决了吗？ 我用5060ti 运行之后和你这个一样的报错

5060 ti 16G和你一样，解决了劳烦通知下
